// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZYjkxcmSW7vk2yU8AeXTyFFHTfVS6R7Y',
    appId: '1:1092579870813:web:84acfb7b5e7ad6e2d025b4',
    messagingSenderId: '1092579870813',
    projectId: 'aeroponik-39254',
    authDomain: 'aeroponik-39254.firebaseapp.com',
    databaseURL: 'https://aeroponik-39254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aeroponik-39254.firebasestorage.app',
    measurementId: 'G-H8VE5RQ5L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZH7sAjytM2ChoTvF5ErtMkXeMK_GUveU',
    appId: '1:1092579870813:android:fd1a261a707ca5ddd025b4',
    messagingSenderId: '1092579870813',
    projectId: 'aeroponik-39254',
    databaseURL: 'https://aeroponik-39254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aeroponik-39254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxhTllTAAMJy6L3kL-juIPNI-wHQ8X4Wg',
    appId: '1:1092579870813:ios:d40e4fc305b80c33d025b4',
    messagingSenderId: '1092579870813',
    projectId: 'aeroponik-39254',
    databaseURL: 'https://aeroponik-39254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aeroponik-39254.firebasestorage.app',
    iosBundleId: 'com.example.aeroponikapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxhTllTAAMJy6L3kL-juIPNI-wHQ8X4Wg',
    appId: '1:1092579870813:ios:d40e4fc305b80c33d025b4',
    messagingSenderId: '1092579870813',
    projectId: 'aeroponik-39254',
    databaseURL: 'https://aeroponik-39254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aeroponik-39254.firebasestorage.app',
    iosBundleId: 'com.example.aeroponikapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZYjkxcmSW7vk2yU8AeXTyFFHTfVS6R7Y',
    appId: '1:1092579870813:web:01dc33705be1e6d9d025b4',
    messagingSenderId: '1092579870813',
    projectId: 'aeroponik-39254',
    authDomain: 'aeroponik-39254.firebaseapp.com',
    databaseURL: 'https://aeroponik-39254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aeroponik-39254.firebasestorage.app',
    measurementId: 'G-S8BWVPM2Q6',
  );

}